# https://redhat-scholars.github.io/tekton-tutorial/tekton-tutorial/workspaces.html
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: i-b-pr- 
  labels:
    app: poc
spec:
  
  pipelineRef:
    name: image-build-pipeline
  workspaces:
    - name: source-ws 
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi
    - name: dockerconfig-ws
      secret:
        secretName: spiro-redhat-pull-secret