apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
 name: image-build-pipeline
spec:
  workspaces:
   - name: source-ws
   - name: dockerconfig-ws
     optional: true
  params:
   - name: GIT_URL
     type: string
     default: https://github.com/spiro-redhat/fonts.git  
   - name: GIT_REVISION
     type: string
     default: main
   - name: IMAGE_NAME
     type: string
     default: 'eap74-ttf'
   - name: NAMESPACE
     type: string
     default: $(context.pipelineRun.namespace)
  tasks:
    - name: git-clone
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: source-ws
      params:
        - name: url
          value: $(params.GIT_URL) 
        - name: revision
          value: $(params.GIT_REVISION)  
        - name: sslVerify
          value: "false"
    - name: create-dockerfile
      taskRef:
        kind: Task
        name: create-dockerfile
      runAfter:
        - "git-clone"
      workspaces:
        - name: output
          workspace: source-ws
    - name: buildah-image
      taskRef:
        name: buildah
        kind: ClusterTask   
      runAfter:
        - create-dockerfile
      workspaces:
        - name: source
          workspace: source-ws
        - name: dockerconfig
          workspace: dockerconfig-ws
      params:
        #- name: SKIP_PUSH # if you want to skip the push 
        #  value: 'true' 
        - name: IMAGE
          value: 'image-registry.openshift-image-registry.svc:5000/$(params.NAMESPACE)/$(params.IMAGE_NAME):0.2'
        - name: TLSVERIFY
          value: 'false'
      
    
