---
apiVersion: tekton.dev/v1alpha1 
kind: Task
metadata:
  name: build-eap-image
spec:
    
  workspaces:
    - name: output
    - name: gen-config
      mountPath: /docker-gen
    
  params:
    - name: NAMESPACE
      type: string
      default: test
    - name: TLS_VERIFY
      type: string
      default: 'false'
    - name: STORAGE_DRIVER
      type: string
      default: vfs
    - name: IMAGE_STREAM
      type: string   
  results:
    - name: commit
      description: sha signature of image 
    - name: dockerfile
      description: a list of buildah's repo    
  steps:
    - name: create-dockerfile
      image: registry.redhat.io/ocp-tools-43-tech-preview/source-to-image-rhel8
      command: 
        - bin/sh 
        - '-c'
      args: 
        - |-
          echo "FROM  quay.io/spiro-redhat/eap74-openjdk8-runtime-openshift-rhel7:latest" > $(workspaces.gen-config.path)/Dockerfile
          echo "COPY $(workspaces.output.path) /usr/share/fonts/truetype" >> $(workspaces.gen-config.path)/Dockerfile
         
          
    - name: build-image 
      image: registry.redhat.io/rhel8/buildah@sha256:6a68ece207bc5fd8db2dd5cc2d0b53136236fb5178eb5b71eebe5d07a3c33d13
      command: 
        - buildah
        - bud
        - '--log-level'
        - 'info'
        - '--tls-verify=$(params.TLS_VERIFY)'
        - '--storage-driver=$(params.STORAGE_DRIVER)'
        - '--layers'
        - '-f'
        - '$(workspaces.gen-config.path)/Dockerfile'
        - '--root'
        - '/files/buildah-containers'
        - '-t'
        - 'localhost/$(params.NAMESPACE)/$(params.IMAGE_STREAM)'
        - . 
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
     
      
    
    - name: view-image
      image: registry.redhat.io/rhel8/buildah@sha256:6a68ece207bc5fd8db2dd5cc2d0b53136236fb5178eb5b71eebe5d07a3c33d13
      command:
        - buildah
        - images
        - '--log-level'
        - 'info'
        - '--storage-driver=$(params.STORAGE_DRIVER)'
      
      resources: {} 
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
     
    #  securityContext:
    #   privileged: true
         
   # - name: tag-image
   #   image: registry.redhat.io/rhel8/buildah
   #   command: 
   #     - buildah
   #     - tag 
   #     - '--storage-driver=$(params.STORAGE_DRIVER)'
   #     - '$(params.NAMESPACE)/$(params.IMAGE_STREAM)'
   #     - 'eap-7.4.0-ttf'        
    - name: push-image
      image: registry.redhat.io/rhel8/buildah@sha256:6a68ece207bc5fd8db2dd5cc2d0b53136236fb5178eb5b71eebe5d07a3c33d13
      command:
        - buildah
        - push
        - '--log-level'
        - 'debug'
        - --tls-verify=$(params.TLS_VERIFY)
        - '$(params.NAMESPACE)/$(params.IMAGE_STREAM)'
        - 'docker://image-registry.openshift-image-registry.svc:5000/$(params.NAMESPACE)/$(params.IMAGE_STREAM)'
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      
  volumes:
    - name: varlibcontainers
      emptyDir: {}
            
      
    